#pragma once

#define LOG_LOW_ENABLED 0
#define LOG_SOLVER_ENABLED 1
#define LOG_LOCAL_SEARCH_ENABLED 1
#define SRAND_SEED 9
#define USE_PATHFINDING 1
#define USE_ANNEALING 1
#define ANNEALING_TEMP 2.0f
#define ANNEALING_COOLING 0.005f
#define ANNEALING_ITERATIONS 1000
#define HILLCLIMBING_ITERATIONS 1000
#define USE_DATA_LOGGER 1
#define DATA_LOGGER_PREFIX "logs/tmp/sa_"
